# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warningwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningWindow(object):
    def setupUi(self, WarningWindow):
        WarningWindow.setObjectName("WarningWindow")
        WarningWindow.setEnabled(True)
        WarningWindow.resize(360, 270)
        WarningWindow.setMinimumSize(QtCore.QSize(360, 270))
        WarningWindow.setMaximumSize(QtCore.QSize(360, 270))
        WarningWindow.setStyleSheet("QWidget{background:rgb(212, 218, 236)}\n"
"QWidget{border:rgb(212, 218, 236)}")
        self.OKButton = QtWidgets.QPushButton(WarningWindow)
        self.OKButton.setGeometry(QtCore.QRect(110, 170, 141, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton.sizePolicy().hasHeightForWidth())
        self.OKButton.setSizePolicy(sizePolicy)
        self.OKButton.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.OKButton.setObjectName("OKButton")
        self.WarningText = QtWidgets.QLabel(WarningWindow)
        self.WarningText.setGeometry(QtCore.QRect(30, 100, 291, 23))
        self.WarningText.setStyleSheet("font:14pt \"Dubai\";")
        self.WarningText.setObjectName("WarningText")

        self.retranslateUi(WarningWindow)
        QtCore.QMetaObject.connectSlotsByName(WarningWindow)

    def retranslateUi(self, WarningWindow):
        _translate = QtCore.QCoreApplication.translate
        WarningWindow.setWindowTitle(_translate("WarningWindow", "Dialog"))
        self.OKButton.setText(_translate("WarningWindow", "OK"))
        self.WarningText.setText(_translate("WarningWindow", "Warning: Please lock the model."))
