# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.tabWidget.setMaximumSize(QtCore.QSize(1080, 720))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:210}\n"
"QTabBar::tab{height:144}\n"
"QTabBar::tab{color:#2e313f}\n"
"QTabBar::tab:selected{background:#929ae1}\n"
"QTabBar::tab:hover{color:#ffffff}\n"
"QTabBar::tab{background:#abbcec}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QWidget{background:rgb(212, 218, 236)}\n"
"QWidget{border:rgb(212, 218, 236)}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.ModSel = QtWidgets.QWidget()
        self.ModSel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ModSel.setObjectName("ModSel")
        self.Model1 = QtWidgets.QRadioButton(self.ModSel)
        self.Model1.setGeometry(QtCore.QRect(70, 70, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model1.setFont(font)
        self.Model1.setStyleSheet("font: 14pt \"Dubai\";")
        self.Model1.setCheckable(True)
        self.Model1.setChecked(True)
        self.Model1.setObjectName("Model1")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Model1)
        self.Model1Opt1 = QtWidgets.QRadioButton(self.ModSel)
        self.Model1Opt1.setGeometry(QtCore.QRect(90, 110, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model1Opt1.setFont(font)
        self.Model1Opt1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Model1Opt1.setStatusTip("")
        self.Model1Opt1.setWhatsThis("")
        self.Model1Opt1.setStyleSheet("font: 14pt \"Dubai\";")
        self.Model1Opt1.setChecked(True)
        self.Model1Opt1.setObjectName("Model1Opt1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Model1Opt1)
        self.Model1Opt2 = QtWidgets.QRadioButton(self.ModSel)
        self.Model1Opt2.setGeometry(QtCore.QRect(90, 150, 381, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model1Opt2.setFont(font)
        self.Model1Opt2.setStyleSheet("font: 14pt \"Dubai\";")
        self.Model1Opt2.setObjectName("Model1Opt2")
        self.buttonGroup.addButton(self.Model1Opt2)
        self.Model1Opt3 = QtWidgets.QRadioButton(self.ModSel)
        self.Model1Opt3.setGeometry(QtCore.QRect(90, 190, 411, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model1Opt3.setFont(font)
        self.Model1Opt3.setStyleSheet("font: 14pt \"Dubai\";\n"
"")
        self.Model1Opt3.setObjectName("Model1Opt3")
        self.buttonGroup.addButton(self.Model1Opt3)
        self.Model2Opt1 = QtWidgets.QCheckBox(self.ModSel)
        self.Model2Opt1.setGeometry(QtCore.QRect(90, 320, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model2Opt1.setFont(font)
        self.Model2Opt1.setStyleSheet("font: 12pt \"Dubai\";")
        self.Model2Opt1.setCheckable(True)
        self.Model2Opt1.setObjectName("Model2Opt1")
        self.Model2Opt3 = QtWidgets.QCheckBox(self.ModSel)
        self.Model2Opt3.setGeometry(QtCore.QRect(310, 320, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model2Opt3.setFont(font)
        self.Model2Opt3.setStyleSheet("font: 12pt \"Dubai\";")
        self.Model2Opt3.setCheckable(True)
        self.Model2Opt3.setObjectName("Model2Opt3")
        self.Model2 = QtWidgets.QRadioButton(self.ModSel)
        self.Model2.setGeometry(QtCore.QRect(70, 290, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model2.setFont(font)
        self.Model2.setStyleSheet("font: 13pt \"Dubai\";")
        self.Model2.setChecked(False)
        self.Model2.setObjectName("Model2")
        self.buttonGroup_2.addButton(self.Model2)
        self.Model2Opt2 = QtWidgets.QCheckBox(self.ModSel)
        self.Model2Opt2.setGeometry(QtCore.QRect(200, 320, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Model2Opt2.setFont(font)
        self.Model2Opt2.setStyleSheet("font: 12pt \"Dubai\";")
        self.Model2Opt2.setCheckable(True)
        self.Model2Opt2.setObjectName("Model2Opt2")
        self.Lock = QtWidgets.QPushButton(self.ModSel)
        self.Lock.setGeometry(QtCore.QRect(90, 380, 131, 31))
        self.Lock.setStyleSheet("QPushButton{\n"
"font: 13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed, QPushButton::checked{\n"
"setText:str(\"Continue\");\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"\n"
"")
        self.Lock.setCheckable(True)
        self.Lock.setAutoRepeat(False)
        self.Lock.setAutoDefault(False)
        self.Lock.setDefault(False)
        self.Lock.setFlat(False)
        self.Lock.setObjectName("Lock")
        self.tabWidget.addTab(self.ModSel, "")
        self.DataFit = QtWidgets.QWidget()
        self.DataFit.setObjectName("DataFit")
        self.Load = QtWidgets.QPushButton(self.DataFit)
        self.Load.setGeometry(QtCore.QRect(600, 85, 101, 31))
        self.Load.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Load.setCheckable(False)
        self.Load.setAutoRepeat(False)
        self.Load.setAutoDefault(False)
        self.Load.setDefault(False)
        self.Load.setFlat(False)
        self.Load.setObjectName("Load")
        self.Confirm = QtWidgets.QPushButton(self.DataFit)
        self.Confirm.setGeometry(QtCore.QRect(720, 85, 101, 31))
        self.Confirm.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Confirm.setObjectName("Confirm")
        self.DataLogBox = QtWidgets.QTextBrowser(self.DataFit)
        self.DataLogBox.setGeometry(QtCore.QRect(40, 190, 411, 431))
        self.DataLogBox.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font:12pt \"Dubai\";\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;")
        self.DataLogBox.setObjectName("DataLogBox")
        self.ProgressBar = QtWidgets.QWidget(self.DataFit)
        self.ProgressBar.setGeometry(QtCore.QRect(30, 130, 751, 41))
        self.ProgressBar.setObjectName("ProgressBar")
        self.FilePath = QtWidgets.QLineEdit(self.DataFit)
        self.FilePath.setGeometry(QtCore.QRect(40, 85, 541, 31))
        self.FilePath.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font:13pt \"Dubai\";\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;")
        self.FilePath.setObjectName("FilePath")
        self.Percentage = QtWidgets.QLabel(self.DataFit)
        self.Percentage.setGeometry(QtCore.QRect(780, 130, 51, 41))
        self.Percentage.setStyleSheet("font:12pt \"Dubai\";\n"
"color:#4e526b;")
        self.Percentage.setObjectName("Percentage")
        self.TrainRatio = QtWidgets.QLineEdit(self.DataFit)
        self.TrainRatio.setGeometry(QtCore.QRect(620, 190, 81, 31))
        self.TrainRatio.setStyleSheet("background-color:#ffffff;\n"
"font:12pt \"Dubai\";\n"
"border-radius:10px;\n"
"\n"
"")
        self.TrainRatio.setAlignment(QtCore.Qt.AlignCenter)
        self.TrainRatio.setObjectName("TrainRatio")
        self.RatioLabel = QtWidgets.QLabel(self.DataFit)
        self.RatioLabel.setGeometry(QtCore.QRect(480, 190, 141, 31))
        self.RatioLabel.setStyleSheet("color:#4e526b;\n"
"font:13pt \"Dubai\";")
        self.RatioLabel.setObjectName("RatioLabel")
        self.RatioLabel2 = QtWidgets.QLabel(self.DataFit)
        self.RatioLabel2.setGeometry(QtCore.QRect(710, 190, 51, 31))
        self.RatioLabel2.setStyleSheet("color:#4e526b;\n"
"font:13pt \"Dubai\";")
        self.RatioLabel2.setObjectName("RatioLabel2")
        self.TestRatio = QtWidgets.QLineEdit(self.DataFit)
        self.TestRatio.setGeometry(QtCore.QRect(620, 230, 81, 31))
        self.TestRatio.setStyleSheet("background-color:#ffffff;\n"
"font: 12pt \"Dubai\";\n"
"border-radius:10px;\n"
"")
        self.TestRatio.setAlignment(QtCore.Qt.AlignCenter)
        self.TestRatio.setReadOnly(True)
        self.TestRatio.setClearButtonEnabled(False)
        self.TestRatio.setObjectName("TestRatio")
        self.RatioLabel3 = QtWidgets.QLabel(self.DataFit)
        self.RatioLabel3.setGeometry(QtCore.QRect(710, 230, 51, 31))
        self.RatioLabel3.setStyleSheet("color:#4e526b;\n"
"font:13pt \"Dubai\";")
        self.RatioLabel3.setObjectName("RatioLabel3")
        self.Confirm2 = QtWidgets.QPushButton(self.DataFit)
        self.Confirm2.setGeometry(QtCore.QRect(720, 190, 101, 31))
        self.Confirm2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Confirm2.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}")
        self.Confirm2.setCheckable(True)
        self.Confirm2.setObjectName("Confirm2")
        self.TestCase = QtWidgets.QListWidget(self.DataFit)
        self.TestCase.setGeometry(QtCore.QRect(470, 190, 241, 401))
        self.TestCase.setStyleSheet("QListWidget{font:12pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;}\n"
"\n"
"QListWidget::item:selected {color:#ffffff;\n"
"background-color:#9fa7e7;}\n"
"QListWidget::item:hover {color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff);}")
        self.TestCase.setObjectName("TestCase")
        self.bgwidget3 = QtWidgets.QWidget(self.DataFit)
        self.bgwidget3.setGeometry(QtCore.QRect(470, 190, 241, 431))
        self.bgwidget3.setStyleSheet("font:12pt \"Dubai\";\n"
"background-color:#8186b0;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;")
        self.bgwidget3.setObjectName("bgwidget3")
        self.TestCaseText = QtWidgets.QLabel(self.bgwidget3)
        self.TestCaseText.setGeometry(QtCore.QRect(0, 400, 131, 31))
        self.TestCaseText.setStyleSheet("color:#ffffff;\n"
"font:14pt \"Dubai\";")
        self.TestCaseText.setObjectName("TestCaseText")
        self.Warning3 = QtWidgets.QLabel(self.DataFit)
        self.Warning3.setGeometry(QtCore.QRect(730, 230, 101, 41))
        self.Warning3.setStyleSheet("font:11pt \"Dubai\";\n"
"color:#c86f63;")
        self.Warning3.setWordWrap(True)
        self.Warning3.setObjectName("Warning3")
        self.RatioLabel4 = QtWidgets.QLabel(self.DataFit)
        self.RatioLabel4.setGeometry(QtCore.QRect(480, 230, 141, 31))
        self.RatioLabel4.setStyleSheet("color:#4e526b;\n"
"font:13pt \"Dubai\";")
        self.RatioLabel4.setObjectName("RatioLabel4")
        self.bgwidget3.raise_()
        self.ProgressBar.raise_()
        self.Percentage.raise_()
        self.Load.raise_()
        self.Confirm.raise_()
        self.DataLogBox.raise_()
        self.FilePath.raise_()
        self.Confirm2.raise_()
        self.TestCase.raise_()
        self.Warning3.raise_()
        self.TrainRatio.raise_()
        self.RatioLabel.raise_()
        self.RatioLabel2.raise_()
        self.RatioLabel4.raise_()
        self.TestRatio.raise_()
        self.RatioLabel3.raise_()
        self.tabWidget.addTab(self.DataFit, "")
        self.Training = QtWidgets.QWidget()
        self.Training.setObjectName("Training")
        self.GraphWidget = QtWidgets.QWidget(self.Training)
        self.GraphWidget.setGeometry(QtCore.QRect(40, 150, 781, 401))
        self.GraphWidget.setStyleSheet("")
        self.GraphWidget.setObjectName("GraphWidget")
        self.Start = QtWidgets.QPushButton(self.Training)
        self.Start.setGeometry(QtCore.QRect(460, 40, 171, 31))
        self.Start.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"\n"
"")
        self.Start.setCheckable(False)
        self.Start.setAutoRepeat(False)
        self.Start.setAutoDefault(False)
        self.Start.setDefault(False)
        self.Start.setFlat(False)
        self.Start.setObjectName("Start")
        self.Pause = QtWidgets.QPushButton(self.Training)
        self.Pause.setGeometry(QtCore.QRect(650, 40, 171, 31))
        self.Pause.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed, QPushButton::checked{\n"
"setText:str(\"Continue\");\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"\n"
"")
        self.Pause.setCheckable(True)
        self.Pause.setAutoRepeat(False)
        self.Pause.setAutoDefault(False)
        self.Pause.setDefault(False)
        self.Pause.setFlat(False)
        self.Pause.setObjectName("Pause")
        self.Stop = QtWidgets.QPushButton(self.Training)
        self.Stop.setGeometry(QtCore.QRect(650, 80, 171, 31))
        self.Stop.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"\n"
"")
        self.Stop.setCheckable(False)
        self.Stop.setAutoRepeat(False)
        self.Stop.setAutoDefault(False)
        self.Stop.setDefault(False)
        self.Stop.setFlat(False)
        self.Stop.setObjectName("Stop")
        self.EpochValue = QtWidgets.QLineEdit(self.Training)
        self.EpochValue.setGeometry(QtCore.QRect(320, 40, 111, 31))
        self.EpochValue.setStyleSheet("background-color:#ffffff;\n"
"font: 12pt \"Dubai\";\n"
"border-radius:10px;\n"
"\n"
"")
        self.EpochValue.setObjectName("EpochValue")
        self.label = QtWidgets.QLabel(self.Training)
        self.label.setGeometry(QtCore.QRect(250, 40, 61, 31))
        self.label.setStyleSheet("font:13pt \"Dubai\";\n"
"color:#4e526b;")
        self.label.setObjectName("label")
        self.TrainingLogBox = QtWidgets.QTextBrowser(self.Training)
        self.TrainingLogBox.setGeometry(QtCore.QRect(50, 570, 771, 101))
        self.TrainingLogBox.setStyleSheet("font:11pt \"Dubai\";")
        self.TrainingLogBox.setObjectName("TrainingLogBox")
        self.ProgressNoticer = QtWidgets.QLabel(self.Training)
        self.ProgressNoticer.setGeometry(QtCore.QRect(50, 110, 291, 31))
        self.ProgressNoticer.setStyleSheet("font:13pt \"Dubai\";\n"
"color:#c86f63;")
        self.ProgressNoticer.setObjectName("ProgressNoticer")
        self.ImpleNoticer = QtWidgets.QLabel(self.Training)
        self.ImpleNoticer.setGeometry(QtCore.QRect(350, 110, 261, 31))
        self.ImpleNoticer.setStyleSheet("font:13pt \"Dubai\";\n"
"color:#c86f63;")
        self.ImpleNoticer.setObjectName("ImpleNoticer")
        self.tabWidget.addTab(self.Training, "")
        self.Output = QtWidgets.QWidget()
        self.Output.setObjectName("Output")
        self.OutputConfirm = QtWidgets.QPushButton(self.Output)
        self.OutputConfirm.setGeometry(QtCore.QRect(270, 140, 131, 31))
        self.OutputConfirm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OutputConfirm.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}")
        self.OutputConfirm.setCheckable(True)
        self.OutputConfirm.setObjectName("OutputConfirm")
        self.CaseOption = QtWidgets.QListWidget(self.Output)
        self.CaseOption.setGeometry(QtCore.QRect(50, 60, 211, 431))
        self.CaseOption.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CaseOption.setStyleSheet("QListWidget{font:12pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;}\n"
"\n"
"QListWidget::item:selected {color:#ffffff;\n"
"background-color:#9fa7e7;}\n"
"QListWidget::item:hover {color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff);}")
        self.CaseOption.setObjectName("CaseOption")
        self.OutputLoad = QtWidgets.QPushButton(self.Output)
        self.OutputLoad.setGeometry(QtCore.QRect(270, 100, 131, 31))
        self.OutputLoad.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.OutputLoad.setCheckable(False)
        self.OutputLoad.setAutoRepeat(False)
        self.OutputLoad.setAutoDefault(False)
        self.OutputLoad.setDefault(False)
        self.OutputLoad.setFlat(False)
        self.OutputLoad.setObjectName("OutputLoad")
        self.OutputConfirm2 = QtWidgets.QPushButton(self.Output)
        self.OutputConfirm2.setGeometry(QtCore.QRect(690, 140, 131, 31))
        self.OutputConfirm2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OutputConfirm2.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}")
        self.OutputConfirm2.setCheckable(True)
        self.OutputConfirm2.setObjectName("OutputConfirm2")
        self.ModelOption = QtWidgets.QListWidget(self.Output)
        self.ModelOption.setGeometry(QtCore.QRect(420, 60, 261, 431))
        self.ModelOption.setStyleSheet("QListWidget{font:12pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;}\n"
"\n"
"QListWidget::item:selected {color:#ffffff;\n"
"background-color:#9fa7e7;}\n"
"QListWidget::item:hover {color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff);}")
        self.ModelOption.setObjectName("ModelOption")
        self.OutputLoad2 = QtWidgets.QPushButton(self.Output)
        self.OutputLoad2.setGeometry(QtCore.QRect(690, 100, 131, 31))
        self.OutputLoad2.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.OutputLoad2.setCheckable(False)
        self.OutputLoad2.setAutoRepeat(False)
        self.OutputLoad2.setAutoDefault(False)
        self.OutputLoad2.setDefault(False)
        self.OutputLoad2.setFlat(False)
        self.OutputLoad2.setObjectName("OutputLoad2")
        self.bgwidget = QtWidgets.QWidget(self.Output)
        self.bgwidget.setGeometry(QtCore.QRect(50, 120, 211, 401))
        self.bgwidget.setStyleSheet("font:12pt \"Dubai\";\n"
"background-color:#8186b0;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;")
        self.bgwidget.setObjectName("bgwidget")
        self.CaseText = QtWidgets.QLabel(self.bgwidget)
        self.CaseText.setGeometry(QtCore.QRect(0, 370, 91, 31))
        self.CaseText.setStyleSheet("color:#ffffff;\n"
"font:14pt \"Dubai\";")
        self.CaseText.setObjectName("CaseText")
        self.bgwidget2 = QtWidgets.QWidget(self.Output)
        self.bgwidget2.setGeometry(QtCore.QRect(420, 90, 261, 431))
        self.bgwidget2.setStyleSheet("font:12pt \"Dubai\";\n"
"background-color:#8186b0;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"alternate-background-color:beige;")
        self.bgwidget2.setObjectName("bgwidget2")
        self.ModelText = QtWidgets.QLabel(self.bgwidget2)
        self.ModelText.setGeometry(QtCore.QRect(0, 400, 91, 31))
        self.ModelText.setStyleSheet("color:#ffffff;\n"
"font:14pt \"Dubai\";")
        self.ModelText.setObjectName("ModelText")
        self.Compute = QtWidgets.QPushButton(self.Output)
        self.Compute.setGeometry(QtCore.QRect(690, 560, 131, 31))
        self.Compute.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Compute.setCheckable(False)
        self.Compute.setAutoRepeat(False)
        self.Compute.setAutoDefault(False)
        self.Compute.setDefault(False)
        self.Compute.setFlat(False)
        self.Compute.setObjectName("Compute")
        self.Warning = QtWidgets.QLabel(self.Output)
        self.Warning.setGeometry(QtCore.QRect(280, 180, 91, 41))
        self.Warning.setStyleSheet("font:11pt \"Dubai\";\n"
"color:#c86f63;")
        self.Warning.setWordWrap(True)
        self.Warning.setObjectName("Warning")
        self.Warning2 = QtWidgets.QLabel(self.Output)
        self.Warning2.setGeometry(QtCore.QRect(700, 180, 101, 41))
        self.Warning2.setStyleSheet("font:11pt \"Dubai\";\n"
"color:#c86f63;")
        self.Warning2.setWordWrap(True)
        self.Warning2.setObjectName("Warning2")
        self.Finished = QtWidgets.QLabel(self.Output)
        self.Finished.setGeometry(QtCore.QRect(710, 600, 101, 21))
        self.Finished.setStyleSheet("font:13pt \"Dubai\";\n"
"color:#c86f63;")
        self.Finished.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Finished.setObjectName("Finished")
        self.OutputLoad3 = QtWidgets.QPushButton(self.Output)
        self.OutputLoad3.setGeometry(QtCore.QRect(270, 60, 131, 31))
        self.OutputLoad3.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.OutputLoad3.setCheckable(False)
        self.OutputLoad3.setAutoRepeat(False)
        self.OutputLoad3.setAutoDefault(False)
        self.OutputLoad3.setDefault(False)
        self.OutputLoad3.setFlat(False)
        self.OutputLoad3.setObjectName("OutputLoad3")
        self.OutputLoad4 = QtWidgets.QPushButton(self.Output)
        self.OutputLoad4.setGeometry(QtCore.QRect(690, 60, 131, 31))
        self.OutputLoad4.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:10px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.OutputLoad4.setCheckable(False)
        self.OutputLoad4.setAutoRepeat(False)
        self.OutputLoad4.setAutoDefault(False)
        self.OutputLoad4.setDefault(False)
        self.OutputLoad4.setFlat(False)
        self.OutputLoad4.setObjectName("OutputLoad4")
        self.bgwidget2.raise_()
        self.bgwidget.raise_()
        self.OutputConfirm.raise_()
        self.CaseOption.raise_()
        self.OutputLoad.raise_()
        self.OutputConfirm2.raise_()
        self.ModelOption.raise_()
        self.OutputLoad2.raise_()
        self.Compute.raise_()
        self.Warning.raise_()
        self.Warning2.raise_()
        self.Finished.raise_()
        self.OutputLoad3.raise_()
        self.OutputLoad4.raise_()
        self.tabWidget.addTab(self.Output, "")
        self.Visulization = QtWidgets.QWidget()
        self.Visulization.setAutoFillBackground(False)
        self.Visulization.setObjectName("Visulization")
        self.XYZ = QtWidgets.QPushButton(self.Visulization)
        self.XYZ.setGeometry(QtCore.QRect(670, 50, 151, 31))
        self.XYZ.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.XYZ.setCheckable(True)
        self.XYZ.setChecked(True)
        self.XYZ.setObjectName("XYZ")
        self.Xview = QtWidgets.QPushButton(self.Visulization)
        self.Xview.setGeometry(QtCore.QRect(670, 80, 151, 31))
        self.Xview.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Xview.setCheckable(True)
        self.Xview.setObjectName("Xview")
        self.Set = QtWidgets.QPushButton(self.Visulization)
        self.Set.setGeometry(QtCore.QRect(670, 270, 151, 31))
        self.Set.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Set.setCheckable(False)
        self.Set.setObjectName("Set")
        self.Zview = QtWidgets.QPushButton(self.Visulization)
        self.Zview.setGeometry(QtCore.QRect(670, 140, 151, 31))
        self.Zview.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Zview.setCheckable(True)
        self.Zview.setObjectName("Zview")
        self.Yview = QtWidgets.QPushButton(self.Visulization)
        self.Yview.setGeometry(QtCore.QRect(670, 110, 151, 31))
        self.Yview.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Yview.setCheckable(True)
        self.Yview.setObjectName("Yview")
        self.ViewPort = QtWidgets.QOpenGLWidget(self.Visulization)
        self.ViewPort.setGeometry(QtCore.QRect(50, 50, 621, 591))
        self.ViewPort.setObjectName("ViewPort")
        self.ViewIndex = QtWidgets.QTextEdit(self.Visulization)
        self.ViewIndex.setGeometry(QtCore.QRect(670, 170, 151, 101))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.ViewIndex.setFont(font)
        self.ViewIndex.setStyleSheet("font:11pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;")
        self.ViewIndex.setObjectName("ViewIndex")
        self.ViewPortLog = QtWidgets.QTextBrowser(self.Visulization)
        self.ViewPortLog.setGeometry(QtCore.QRect(670, 310, 151, 291))
        self.ViewPortLog.setStyleSheet("font:11pt \"Dubai\";")
        self.ViewPortLog.setObjectName("ViewPortLog")
        self.Copy = QtWidgets.QPushButton(self.Visulization)
        self.Copy.setGeometry(QtCore.QRect(670, 610, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Copy.setFont(font)
        self.Copy.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Copy.setIcon(icon)
        self.Copy.setIconSize(QtCore.QSize(20, 20))
        self.Copy.setCheckable(False)
        self.Copy.setObjectName("Copy")
        self.Save = QtWidgets.QPushButton(self.Visulization)
        self.Save.setGeometry(QtCore.QRect(700, 610, 31, 31))
        self.Save.setStyleSheet("QPushButton{\n"
"font:13pt \"Dubai\";\n"
"color:#4e526b;\n"
"background-color:#f6f5ff;\n"
"border-radius:5px;\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color:#8186b0;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#ffffff;\n"
"background-color:#9fa7e7;\n"
"border-color:#8186b0;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"color:#ffffff;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #9099d1, stop:1 #b0bbff)\n"
"}\n"
"")
        self.Save.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save.setIcon(icon1)
        self.Save.setIconSize(QtCore.QSize(19, 19))
        self.Save.setCheckable(False)
        self.Save.setObjectName("Save")
        self.ViewPortLog.raise_()
        self.ViewPort.raise_()
        self.Xview.raise_()
        self.Set.raise_()
        self.Zview.raise_()
        self.Yview.raise_()
        self.XYZ.raise_()
        self.ViewIndex.raise_()
        self.Copy.raise_()
        self.Save.raise_()
        self.tabWidget.addTab(self.Visulization, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Banira AI - v1.0"))
        self.Model1.setText(_translate("MainWindow", "Seperate Channel Alex Net"))
        self.Model1Opt1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">self test with customized test ratio</span></p></body></html>"))
        self.Model1Opt1.setText(_translate("MainWindow", "self to self"))
        self.Model1Opt2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">customize a test set and isolate the test set</span></p></body></html>"))
        self.Model1Opt2.setText(_translate("MainWindow", "other to self"))
        self.Model1Opt3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">customize a test set but not isolate the test set</span></p></body></html>"))
        self.Model1Opt3.setText(_translate("MainWindow", "all to self"))
        self.Model2Opt1.setText(_translate("MainWindow", "CheckBox"))
        self.Model2Opt3.setText(_translate("MainWindow", "CheckBox"))
        self.Model2.setText(_translate("MainWindow", "Model 2"))
        self.Model2Opt2.setText(_translate("MainWindow", "CheckBox"))
        self.Lock.setText(_translate("MainWindow", "Lock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ModSel), _translate("MainWindow", "Model Selection"))
        self.Load.setText(_translate("MainWindow", "Load"))
        self.Confirm.setText(_translate("MainWindow", "Confirm"))
        self.DataLogBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logbox</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Percentage.setText(_translate("MainWindow", "TextLabel"))
        self.TrainRatio.setText(_translate("MainWindow", "90"))
        self.RatioLabel.setText(_translate("MainWindow", "Training set ratio:"))
        self.RatioLabel2.setText(_translate("MainWindow", "%"))
        self.TestRatio.setText(_translate("MainWindow", "10"))
        self.RatioLabel3.setText(_translate("MainWindow", "%"))
        self.Confirm2.setText(_translate("MainWindow", "Confirm"))
        self.TestCaseText.setText(_translate("MainWindow", "Test Set Case"))
        self.Warning3.setText(_translate("MainWindow", "Warning"))
        self.RatioLabel4.setText(_translate("MainWindow", "Test set ratio:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataFit), _translate("MainWindow", "Data Fitting"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.Pause.setText(_translate("MainWindow", "Pause"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.EpochValue.setText(_translate("MainWindow", "800"))
        self.label.setText(_translate("MainWindow", "Epoch:"))
        self.TrainingLogBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS UI Gothic\'; font-size:9pt;\">TRAINING LOG</span></p></body></html>"))
        self.ProgressNoticer.setText(_translate("MainWindow", "ProgressNoticer"))
        self.ImpleNoticer.setText(_translate("MainWindow", "ImplementationNoticer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Training), _translate("MainWindow", "Training Process"))
        self.OutputConfirm.setText(_translate("MainWindow", "Confirm"))
        self.OutputLoad.setText(_translate("MainWindow", "Load file"))
        self.OutputConfirm2.setText(_translate("MainWindow", "Confirm"))
        self.OutputLoad2.setText(_translate("MainWindow", "Load file"))
        self.CaseText.setText(_translate("MainWindow", "Case"))
        self.ModelText.setText(_translate("MainWindow", "Model"))
        self.Compute.setText(_translate("MainWindow", "Compute"))
        self.Warning.setText(_translate("MainWindow", "Warning"))
        self.Warning2.setText(_translate("MainWindow", "Warning"))
        self.Finished.setText(_translate("MainWindow", "Finished"))
        self.OutputLoad3.setText(_translate("MainWindow", "Load folder"))
        self.OutputLoad4.setText(_translate("MainWindow", "Load folder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Output), _translate("MainWindow", "Implementation"))
        self.XYZ.setText(_translate("MainWindow", "Axis"))
        self.Xview.setText(_translate("MainWindow", "X View"))
        self.Set.setText(_translate("MainWindow", "View Set"))
        self.Zview.setText(_translate("MainWindow", "Z View"))
        self.Yview.setText(_translate("MainWindow", "Y View"))
        self.ViewPortLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS UI Gothic\';\">Case name:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS UI Gothic\';\">Model implied:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visulization), _translate("MainWindow", "Visualization"))
